import localFont from "next/font/local";
import "./globals.css";
import { TransactionProvider } from "@/components/context/context";
import { Toaster } from "react-hot-toast";
import NextTopLoader from "nextjs-toploader";
import AdvLayout from "@/components/Layout/AdvLayout";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <TransactionProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-200`}
        >
          <NextTopLoader />
          <Toaster position="top-right" reverseOrder={false} />
          <AdvLayout>{ children }</AdvLayout>
        </body>
      </TransactionProvider>
    </html>
  );
}
